<#
.SYNOPSIS
    Generates tools/crypttest_vec.h - a fixed RSA test vector compiled into the
    crypttest harness.

.DESCRIPTION
    The DOS build of crypttest has to run without any file plumbing inside the
    QEMU VM, so the signature it checks is baked in.

    What lands in the header is a throwaway key's PUBLIC modulus plus a
    signature over a fixed string. There is no secret in it - the private key is
    generated here and discarded - and it has nothing to do with the keys that
    sign real releases.

    Only rerun this if the vector needs replacing; the generated header is
    committed so the test is reproducible.

.EXAMPLE
    pwsh tools/gen-testvector.ps1
#>
[CmdletBinding()]
param([string]$OpenSsl)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\_common.ps1"

$openssl = Resolve-OpenSsl -Explicit $OpenSsl
$work = Join-Path ([System.IO.Path]::GetTempPath()) "ftp4dos-testvec"
if (Test-Path $work) { Remove-Item -Recurse -Force $work }
New-Item -ItemType Directory -Force -Path $work | Out-Null

# The message is a realistic manifest, so the vector also documents the exact
# byte layout the DOS client will hash.
$msg = "# FTP4DOS update manifest`nversion=1.0.2`ndate=2026-08-15`nsize=272104`nsha256=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08`nfile=/FTP4DOS/FTP4DOS.EXE`nnotes=test vector`n"

Push-Location $work
try {
    [System.IO.File]::WriteAllText("$work\msg.txt", $msg, (New-Object System.Text.UTF8Encoding $false))
    & $openssl genrsa -out a.pem 2048 2>$null
    & $openssl genrsa -out b.pem 2048 2>$null
    & $openssl rsa -in a.pem -pubout -out ap.pem 2>$null
    & $openssl rsa -in b.pem -pubout -out bp.pem 2>$null
    & $openssl dgst -sha256 -sign a.pem -out sig.bin msg.txt

    $modA = Get-ModulusBytes -OpenSslExe $openssl -PubPem "$work\ap.pem"
    $modB = Get-ModulusBytes -OpenSslExe $openssl -PubPem "$work\bp.pem"
    $sig  = [System.IO.File]::ReadAllBytes("$work\sig.bin")
    if ($sig.Length -ne 256) { throw "signature is $($sig.Length) bytes, expected 256" }
}
finally { Pop-Location }

function Format-Bytes {
    param([byte[]]$Bytes, [string]$Name)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("static const unsigned char $Name[$($Bytes.Length)] = {")
    for ($i = 0; $i -lt $Bytes.Length; $i += 12) {
        $slice = $Bytes[$i..([Math]::Min($i + 11, $Bytes.Length - 1))]
        $line = ($slice | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', '
        $suffix = if (($i + 12) -lt $Bytes.Length) { ',' } else { '' }
        [void]$sb.AppendLine("    $line$suffix")
    }
    [void]$sb.AppendLine("};")
    return $sb.ToString()
}

# C string literal, one source line per manifest line.
$esc = ($msg -split "`n" | ForEach-Object { '    "' + ($_ -replace '\\', '\\' -replace '"', '\"') + '\n"' })
# The trailing newline produced an empty final element; drop its stray literal.
$esc = $esc[0..($esc.Count - 2)]
$msgLit = ($esc -join "`n")

$content = @"
/* Generated by tools/gen-testvector.ps1 - do not edit by hand.
 *
 * Fixed RSA-2048 test vector compiled into crypttest so the DOS build can run
 * self-contained inside the QEMU VM, with no files to stage.
 *
 * This is throwaway material: a discarded key's public modulus and a signature
 * over the fixed string below. It contains no secret and is unrelated to the
 * keys that sign real releases.
 */
#ifndef CRYPTTEST_VEC_H
#define CRYPTTEST_VEC_H

/* The signed message (a realistic manifest, hashed exactly as received). */
static const char TESTVEC_MSG[] =
$msgLit;

$(Format-Bytes -Bytes $modA -Name 'TESTVEC_MODULUS')
$(Format-Bytes -Bytes $sig -Name 'TESTVEC_SIG')
/* An unrelated key, for the "signature from a different key" case. */
$(Format-Bytes -Bytes $modB -Name 'TESTVEC_MODULUS_OTHER')
#endif /* CRYPTTEST_VEC_H */
"@

$outPath = Join-Path $PSScriptRoot 'crypttest_vec.h'
[System.IO.File]::WriteAllText($outPath, ($content -replace "`r`n", "`n"), (New-Object System.Text.UTF8Encoding $false))
Write-Host "wrote $outPath"
Remove-Item -Recurse -Force $work
