PATH=C:\DOS71;C:\DOS71\norton
SET DIRCMD=/4
MODE CON RATE=32 DELAY=1
MODE CON CP PREPARE=((850)C:\DOS71\EGA.CPI)
MODE CON CP SELECT=850
LH KEYB GR,,C:\DOS71\KEYBOARD.SYS
LH KILLER
LH DOSKEY
LH DOSLFN /Z:C:\DOS71\CP850UNI.TBL
LH MSCDEX /D:IDE-CD
REM LH NLSFUNC
LH SHARE /L:30
LH SMARTDRV
LH CTMOUSE
REM For compatibilty purpose:
LH CTMOUSE > NUL
ECHO.
REM For locking volumes to enable "direct disk access":
REM CALL LOCKDRV.BAT
BREAK ON
LFNFOR ON
ECHO Now you are in MS-DOS 7.10 prompt. Type 'HELP' for help.
ECHO.
