/* Generated by tools/pubkey-to-c.ps1 - do not edit by hand.
 *
 * Public keys the updater trusts when verifying the RSA-2048 signature over
 * UPDATE.INF. Two keys are accepted: a shipped binary can never be taught a
 * new key, so the reserve is the only way back if the primary is lost.
 *
 * primary fingerprint: 50:8e:74:14:b8:35:61:e8
 * reserve fingerprint: 5f:6e:81:08:6d:bc:45:e2
 */
#ifndef RSAKEYS_H
#define RSAKEYS_H

#define RSA_MODULUS_BYTES 256

extern const unsigned char rsa_key_primary[RSA_MODULUS_BYTES];
extern const unsigned char rsa_key_reserve[RSA_MODULUS_BYTES];

#endif /* RSAKEYS_H */